version: "3"

services:
  #Nginx services
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - ./config/nginx:/etc/nginx/conf.d

#Docker networks
networks:
  app-network:
    driver: bridge
