version: "3"

services:
  nginx-proxy: #receive the traffic
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:./public_html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt: #generate certifications ssl
    image: duch/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:./public_html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx_fredrikson: #direccionamiento archivo estatico
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./public_html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=gabocarvajal.duckdns.org
      - LETSENCRYPT_HOST=gabocarvajal.duckdns.org
      - LETSENCRYPT_EMAIL=g.carvajal.pizarro@gmail.com

volumes:
  certs:
  html:
  vhostd:
  confd:
