version: "3"

services:
  #Nginx services
  servernginx:
    image: nginx:alpine
    container_name: servernginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: "America/Santiago"
    networks:
      - app-network
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./public_html:/public_html

#Docker networks
networks:
  app-network:
    driver: bridge
