version: "3"

services:
  #Nginx services
  servernginx:
    image: nginx:alpine
    container_name: servernginx
    restart: unless-stopped #reiniciarse a menos que se detenga
    tty: true
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: "America/Santiago"
    networks:
      - app-network
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./public_html:/public_html
      - ./config/data:/etc/letsencrypt
      - ./config/logs:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbotnginx
    volumes:
      - ./config/data:/etc/letsencrypt
      - ./config/logs:/var/lib/letsencrypt
      - ./public_html:/public_html
    depends_on:
      - servernginx
    command: certonly --webroot --webroot-path=/public_html --email g.carvajal.pizarro@gmail.com --agree-tos --no-eff-email --staging -d webcrapp.ddns.net

#Docker networks
networks:
  app-network:
    driver: bridge
